export const VERSION=1,TOTAL_LEVELS=5,MAX_ATTEMPTS=7,MAX_SCORE=50,STORAGE_KEY='aws-level-devil:v1';
const clone=v=>JSON.parse(JSON.stringify(v));
export function pointsForAttempt(n){return!Number.isInteger(n)||n<1||n>7?0:n<=3?10:13-n}
export function createState({official=true,now=Date.now(),attemptId=globalThis.crypto?.randomUUID?.()||`level-devil-${now}`,level=0}={}){return{version:1,attemptId,official:Boolean(official),status:'active',currentLevel:official?0:Math.max(0,Math.min(4,Number(level)||0)),currentAttempt:1,score:0,completedLevels:0,failedLevel:null,levelResults:[],totalDeaths:0,startedAt:now,completedAt:null,completionNotifiedAt:null,inLevel:false,lastAttemptReason:null}}
export const enterLevel=s=>!s||s.status!=='active'?s:{...clone(s),inLevel:true};
export function consumeAttempt(s,reason='death',now=Date.now()){if(!s||s.status!=='active')return s;const n=clone(s);n.totalDeaths++;n.lastAttemptReason=reason;n.inLevel=false;if(!n.official)return n;if(n.currentAttempt>=7){n.status='failed';n.failedLevel=n.currentLevel+1;n.completedAt=now;n.levelResults.push({level:n.currentLevel+1,attempts:7,points:0,outcome:'failed'})}else n.currentAttempt++;return n}
export function completeLevel(s,now=Date.now()){if(!s||s.status!=='active')return s;const n=clone(s),points=n.official?pointsForAttempt(n.currentAttempt):0;n.levelResults.push({level:n.currentLevel+1,attempts:n.currentAttempt,points,outcome:'complete'});n.score+=points;n.completedLevels++;n.inLevel=false;if(!n.official)return n;if(n.currentLevel===4){n.status='complete';n.completedAt=now}else{n.currentLevel++;n.currentAttempt=1;n.lastAttemptReason=null}return n}
export const serializeState=s=>JSON.stringify(s);
export function restoreState(raw,now=Date.now()){try{const s=JSON.parse(raw);if(!s||s.version!==1||s.official!==true||!['active','complete','failed'].includes(s.status)||!Number.isInteger(s.currentLevel)||s.currentLevel<0||s.currentLevel>4||!Number.isInteger(s.currentAttempt)||s.currentAttempt<1||s.currentAttempt>7)return null;return s.status==='active'&&s.inLevel?consumeAttempt(s,'reload',now):s}catch{return null}}
export const buildCompletionPayload=s=>({game:'aws-level-devil',version:1,attemptId:s.attemptId,official:true,status:s.status,score:s.score,maxScore:50,completedLevels:s.completedLevels,totalLevels:5,failedLevel:s.failedLevel,levelResults:clone(s.levelResults),totalDeaths:s.totalDeaths,startedAt:s.startedAt,completedAt:s.completedAt});
