import { useEffect, useRef, useState } from 'react';
import { createAsteroidCommandEngine } from './asteroidCommandEngine';
import { summarizeAsteroidTournament } from './asteroidCommandCore';
import './asteroidCommand.css';

const blank={score:0,shield:100,stage:1,multiplier:1,destroyed:0,survival:0};
const keyMap={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',' ':'fire'};

export default function AsteroidCommand({onExit,onComplete}){
  const hostRef=useRef(null),engineRef=useRef(null);const[screen,setScreen]=useState('landing'),[attempts,setAttempts]=useState([]),[hud,setHud]=useState(blank),[muted,setMuted]=useState(false);
  useEffect(()=>{engineRef.current=createAsteroidCommandEngine(hostRef.current,{onUpdate:setHud,onFinish:r=>setAttempts(current=>{const next=[...current,r];setScreen(next.length===5?'complete':'attempt');if(next.length===5)onComplete?.({official:true,score:summarizeAsteroidTournament(next.map(a=>a.score)).bestScore,attempts:next});try{const high=Math.max(Number(localStorage.getItem('aws_space_high_score'))||0,r.score);localStorage.setItem('aws_space_high_score',String(high))}catch{/* storage optional */}return next})});const handle=value=>e=>{const action=keyMap[e.key];if(action){e.preventDefault();engineRef.current?.setInput(action,value)}};const down=handle(true),up=handle(false),resize=()=>engineRef.current?.resize();window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('resize',resize);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('resize',resize);engineRef.current?.destroy()}},[onComplete]);
  const start=()=>{setScreen('playing');engineRef.current?.start()},reset=()=>{setAttempts([]);setHud(blank);setScreen('landing')},last=attempts.at(-1),summary=summarizeAsteroidTournament(attempts.map(a=>a.score));
  const press=action=><button onPointerDown={()=>engineRef.current?.setInput(action,true)} onPointerUp={()=>engineRef.current?.setInput(action,false)} onPointerLeave={()=>engineRef.current?.setInput(action,false)}>{({left:'◀',right:'▶',up:'▲',down:'▼',fire:'FIRE'})[action]}</button>;
  return <main className="ac-game"><div className="ac-shell"><div className="ac-stage" ref={hostRef}/><header className="ac-toolbar"><button onClick={onExit}>← Games</button><span>AWS // ASTEROID COMMAND</span><button onClick={()=>setMuted(v=>{engineRef.current?.mute(!v);return !v})}>{muted?'Sound off':'Sound on'}</button></header>
    {screen==='playing'&&<section className="ac-hud"><div><small>Stage</small><b>{String(hud.stage).padStart(2,'0')}</b><small>Attempt {attempts.length+1}/5</small></div><div><small>Shield integrity</small><i><span style={{width:`${hud.shield}%`}}/></i><b>{hud.shield}%</b></div><div><small>Score</small><b>{String(hud.score).padStart(6,'0')}</b><small>{hud.destroyed} destroyed</small></div><div><small>Multiplier</small><b>×{hud.multiplier}</b><small>{Math.floor(hud.survival/60)}:{String(Math.floor(hud.survival%60)).padStart(2,'0')}</small></div></section>}
    {screen==='landing'&&<section className="ac-overlay"><p className="eyebrow">3D AWS SPACE DEFENSE</p><h1>Asteroid <em>Command</em></h1><p>Pilot the cloud defense ship, break incoming asteroids with dual lasers, and protect your shield through five tournament attempts.</p><div className="ac-rules"><span>WASD / ARROWS</span> Navigate <span>SPACE</span> Fire lasers <span>5 ATTEMPTS</span> Best score awards points</div><button className="ac-primary" onClick={start}>Launch mission · attempt 1/5</button><button className="ac-link" onClick={onExit}>Back to games</button></section>}
    {screen==='attempt'&&<section className="ac-overlay"><p className="eyebrow">ATTEMPT {attempts.length}/5 COMPLETE</p><h2 className="failure">SHIP INTEGRITY COMPROMISED</h2><div className="ac-stats"><span>Score <b>{last.score}</b></span><span>Asteroids <b>{last.destroyed}</b></span><span>Stage <b>{last.stage}</b></span><span>Survival <b>{Math.floor(last.survival)}s</b></span></div><button className="ac-primary" onClick={start}>Launch attempt {attempts.length+1}/5</button><button className="ac-link" onClick={onExit}>Back to games</button></section>}
    {screen==='complete'&&<section className="ac-overlay"><p className="eyebrow">TOURNAMENT COMPLETE</p><h2>Mission telemetry</h2><div className="ac-stats"><span>Best score <b>{summary.bestScore}</b></span><span>Team points <b>{summary.points}</b></span></div><ol>{attempts.map((a,i)=><li key={i}><span>Attempt {i+1}</span><b>{a.score}</b><em>STAGE {a.stage}</em></li>)}</ol><button className="ac-primary" onClick={reset}>Redeploy tournament</button><button className="ac-link" onClick={onExit}>Back to games</button></section>}
    <nav className="ac-touch"><div>{press('up')}<span>{press('left')}{press('down')}{press('right')}</span></div>{press('fire')}</nav>
  </div></main>
}
