import * as THREE from 'three';
import { asteroidStage } from './asteroidCommandCore';

export function createAsteroidCommandEngine(host, callbacks={}){
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x03070d);scene.fog=new THREE.FogExp2(0x03070d,.018);
  const camera=new THREE.PerspectiveCamera(55,1,.1,200);camera.position.set(0,0,32);
  const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.appendChild(renderer.domElement);
  const clock=new THREE.Clock();let frame=0,destroyed=false,running=false,muted=false,audio,score=0,shield=100,stage=1,multiplier=1,destroyedCount=0,survival=0,spawnTimer=0,lastShot=0;
  const keys={left:false,right:false,up:false,down:false,fire:false};const asteroids=[],lasers=[],particles=[];
  scene.add(new THREE.AmbientLight(0x6e879f,1.5));const keyLight=new THREE.DirectionalLight(0xff9900,5);keyLight.position.set(4,8,12);scene.add(keyLight);
  const starsGeometry=new THREE.BufferGeometry();const starData=[];for(let i=0;i<1100;i++)starData.push((Math.random()-.5)*75,(Math.random()-.5)*90,(Math.random()-.5)*45);starsGeometry.setAttribute('position',new THREE.Float32BufferAttribute(starData,3));const starsMaterial=new THREE.PointsMaterial({color:0xa8d9ff,size:.1,transparent:true,opacity:.8});const stars=new THREE.Points(starsGeometry,starsMaterial);scene.add(stars);
  const ship=new THREE.Group();const hull=new THREE.Mesh(new THREE.ConeGeometry(1.05,3.4,5),new THREE.MeshStandardMaterial({color:0xe5edf5,metalness:.8,roughness:.25}));hull.rotation.x=Math.PI;ship.add(hull);const wingMaterial=new THREE.MeshStandardMaterial({color:0xff9900,emissive:0x6c2c00});for(const side of[-1,1]){const wing=new THREE.Mesh(new THREE.BoxGeometry(1.7,.18,1.5),wingMaterial);wing.position.set(side*1.15,.25,.2);wing.rotation.z=side*.18;ship.add(wing)}const flame=new THREE.Mesh(new THREE.ConeGeometry(.4,1.8,8),new THREE.MeshBasicMaterial({color:0x04beff}));flame.position.y=-2;ship.add(flame);ship.position.y=-10;scene.add(ship);
  const laserGeometry=new THREE.CylinderGeometry(.07,.07,1.1,7);const laserMaterial=new THREE.MeshBasicMaterial({color:0xff9900});
  const sound=(frequency,d=.08,type='square')=>{if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=frequency;g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{/* optional */}};
  const disposeObject=obj=>{obj.traverse?.(child=>{child.geometry?.dispose();if(Array.isArray(child.material))child.material.forEach(m=>m.dispose());else child.material?.dispose()})};
  const clearAsteroids=()=>{for(const item of asteroids){scene.remove(item.mesh);disposeObject(item.mesh)}asteroids.splice(0)};
  const clearLasers=()=>{for(const item of lasers)scene.remove(item.mesh);lasers.splice(0)};
  const burst=(position,color,count=14)=>{for(let i=0;i<count;i++){const mesh=new THREE.Mesh(new THREE.SphereGeometry(.08,4,4),new THREE.MeshBasicMaterial({color}));mesh.position.copy(position);scene.add(mesh);particles.push({mesh,velocity:new THREE.Vector3((Math.random()-.5)*9,(Math.random()-.5)*9,(Math.random()-.5)*3),life:.7})}};
  const emit=()=>callbacks.onUpdate?.({score,shield,stage,multiplier,destroyed:destroyedCount,survival});
  const finish=()=>{if(!running)return;running=false;ship.visible=false;burst(ship.position,0xff9900,30);sound(75,.45,'sawtooth');callbacks.onFinish?.({score,destroyed:destroyedCount,stage,survival})};
  const spawn=()=>{if(asteroids.length>18)return;const size=Math.random()>.72?3:Math.random()>.42?2:1;const geometry=new THREE.DodecahedronGeometry(size===3?1.7:size===2?1.05:.62,size===3?1:0);const material=new THREE.MeshStandardMaterial({color:0x66717b,roughness:.9,flatShading:true});const mesh=new THREE.Mesh(geometry,material);mesh.position.set((Math.random()-.5)*27,17,(Math.random()-.5)*3);scene.add(mesh);asteroids.push({mesh,size,radius:size===3?1.7:size===2?1.05:.62,vx:(Math.random()-.5)*2.4,vy:-(4.5+Math.random()*3+stage*.7),spin:(Math.random()-.5)*2.8})};
  const fire=()=>{const now=performance.now();if(!running||now-lastShot<155)return;lastShot=now;for(const dx of[-.65,.65]){const mesh=new THREE.Mesh(laserGeometry,laserMaterial);mesh.position.set(ship.position.x+dx,ship.position.y+1,0);scene.add(mesh);lasers.push({mesh,previous:mesh.position.clone()})}sound(560,.05)};
  const hit=(a,index)=>{const pos=a.mesh.position.clone();scene.remove(a.mesh);disposeObject(a.mesh);asteroids.splice(index,1);burst(pos,0xff9900,a.size*7);score+=({1:250,2:150,3:100}[a.size])*multiplier;destroyedCount++;if(destroyedCount%8===0)multiplier++;stage=asteroidStage(score);sound(150+a.size*50,.12,'sawtooth');emit()};
  const resize=()=>{const width=Math.max(1,host.clientWidth),height=Math.max(1,host.clientHeight);camera.aspect=width/height;camera.updateProjectionMatrix();renderer.setSize(width,height,false)};
  const loop=()=>{if(destroyed)return;const dt=Math.min(.035,clock.getDelta());stars.position.y-=dt*(running?4:1);if(stars.position.y<-25)stars.position.y=25;
    if(running){survival+=dt;spawnTimer+=dt;if(spawnTimer>Math.max(.42,1.35-stage*.08)){spawnTimer=0;spawn()}const dx=(keys.right?1:0)-(keys.left?1:0),dy=(keys.up?1:0)-(keys.down?1:0);ship.position.x=THREE.MathUtils.clamp(ship.position.x+dx*15*dt,-14,14);ship.position.y=THREE.MathUtils.clamp(ship.position.y+dy*12*dt,-13,-6);ship.rotation.z=THREE.MathUtils.lerp(ship.rotation.z,-dx*.45,.15);ship.rotation.x=THREE.MathUtils.lerp(ship.rotation.x,dy*.2,.15);flame.scale.y=1+Math.sin(performance.now()*.025)*.18;if(keys.fire)fire();
      for(let i=lasers.length-1;i>=0;i--){const l=lasers[i];l.previous.copy(l.mesh.position);l.mesh.position.y+=31*dt;if(l.mesh.position.y>18){scene.remove(l.mesh);lasers.splice(i,1)}}
      for(let i=asteroids.length-1;i>=0;i--){const a=asteroids[i];a.mesh.position.y+=a.vy*dt;a.mesh.position.x+=a.vx*dt;a.mesh.rotation.x+=a.spin*dt;a.mesh.rotation.y+=a.spin*.7*dt;if(a.mesh.position.y<-17){scene.remove(a.mesh);disposeObject(a.mesh);asteroids.splice(i,1);continue}let removed=false;for(let j=lasers.length-1;j>=0;j--){if(a.mesh.position.distanceTo(lasers[j].mesh.position)<a.radius+.5){scene.remove(lasers[j].mesh);lasers.splice(j,1);hit(a,i);removed=true;break}}if(!removed&&a.mesh.position.distanceTo(ship.position)<a.radius+1){scene.remove(a.mesh);disposeObject(a.mesh);asteroids.splice(i,1);shield=Math.max(0,shield-(a.size===3?35:a.size===2?20:10));multiplier=1;burst(ship.position,0xffffff,12);sound(110,.18,'sawtooth');emit();if(shield<=0)finish()}}
      emit();
    }
    for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.mesh.position.addScaledVector(p.velocity,dt);p.life-=dt;p.mesh.scale.setScalar(Math.max(.01,p.life));if(p.life<=0){scene.remove(p.mesh);disposeObject(p.mesh);particles.splice(i,1)}}renderer.render(scene,camera);frame=requestAnimationFrame(loop)};
  resize();frame=requestAnimationFrame(loop);
  return{start(){clearAsteroids();clearLasers();for(const p of particles){scene.remove(p.mesh);disposeObject(p.mesh)}particles.splice(0);score=0;shield=100;stage=1;multiplier=1;destroyedCount=0;survival=0;spawnTimer=0;ship.position.set(0,-10,0);ship.visible=true;running=true;clock.getDelta();sound(330,.16);emit()},setInput(name,value){if(name in keys)keys[name]=value},fire,mute(value){muted=value;if(value)audio?.suspend();else audio?.resume()},resize,destroy(){destroyed=true;running=false;cancelAnimationFrame(frame);audio?.close().catch(()=>{});clearAsteroids();clearLasers();for(const p of particles){scene.remove(p.mesh);disposeObject(p.mesh)}particles.splice(0);disposeObject(ship);starsGeometry.dispose();starsMaterial.dispose();laserGeometry.dispose();laserMaterial.dispose();renderer.dispose();renderer.domElement.remove()}};
}
