import { useEffect, useRef, useState } from 'react';
import { createWatergirlFireboyEngine } from './watergirlFireboyEngine';
import { scoreWatergirlAttempt, summarizeWatergirl } from './watergirlFireboyCore';
import './watergirlFireboy.css';

const blank={timer:45,gems:0,total:10,firePortal:false,waterPortal:false};
const keyMap={a:'fireLeft',d:'fireRight',w:'fireJump',ArrowLeft:'waterLeft',ArrowRight:'waterRight',ArrowUp:'waterJump'};

export default function WatergirlFireboy({onExit,onComplete}){
  const canvasRef=useRef(null),engineRef=useRef(null);const[screen,setScreen]=useState('landing'),[attempts,setAttempts]=useState([]),[hud,setHud]=useState(blank),[muted,setMuted]=useState(false);
  useEffect(()=>{engineRef.current=createWatergirlFireboyEngine(canvasRef.current,{onUpdate:setHud,onFinish:r=>setAttempts(current=>{const scored=scoreWatergirlAttempt(r);const next=[...current,{...r,...scored,score:scored.total}];setScreen(next.length===5?'complete':'attempt');if(next.length===5)onComplete?.({official:true,highestLevel:next.filter(a=>a.success).length,totalDeaths:next.filter(a=>!a.success).length,attempts:next});return next})});
    const handle=(value)=>(e)=>{const action=keyMap[e.key];if(action){e.preventDefault();engineRef.current?.setInput(action,value)}};const down=handle(true),up=handle(false);window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);engineRef.current?.destroy()}},[onComplete]);
  const start=()=>{setScreen('playing');engineRef.current?.start()},reset=()=>{setAttempts([]);setHud(blank);setScreen('landing')},last=attempts.at(-1),summary=summarizeWatergirl(attempts);
  const touch=(action)=><button onPointerDown={()=>engineRef.current?.setInput(action,true)} onPointerUp={()=>engineRef.current?.setInput(action,false)} onPointerLeave={()=>engineRef.current?.setInput(action,false)}>{action.endsWith('Left')?'◀':action.endsWith('Right')?'▶':'▲'}</button>;
  return <main className="wf-game"><div className="wf-shell"><canvas ref={canvasRef} aria-label="AWS Watergirl Fireboy game canvas"/><header className="wf-toolbar"><button onClick={onExit}>← Games</button><span>AWS // ELEMENT PROTOCOL</span><button onClick={()=>setMuted(v=>{engineRef.current?.mute(!v);return !v})}>{muted?'Sound off':'Sound on'}</button></header>
    {screen==='playing'&&<section className="wf-hud"><div><small>Attempt</small><b>{attempts.length+1} / 5</b></div><div className={hud.timer<10?'danger':''}><small>Remaining</small><b>{Math.ceil(hud.timer)}s</b></div><div><small>Gems</small><b>{hud.gems}/{hud.total}</b></div><div><small>Portals</small><b><i className={hud.firePortal?'on':''}>F</i> <i className={hud.waterPortal?'on':''}>W</i></b></div></section>}
    {screen==='landing'&&<section className="wf-overlay"><p className="eyebrow">AWS DUAL-AGENT MISSION</p><h1><em>Fireboy</em> &amp; <strong>Watergirl</strong></h1><p>Move both agents through the cloud facility. Collect gems, avoid the opposite element, and reach both matching portals.</p><div className="wf-rules"><span>Fireboy</span><b>A · D · W</b><span>Watergirl</span><b>← · → · ↑</b><span>Mission</span><b>45 seconds · 5 attempts</b></div><button className="wf-primary" onClick={start}>Start mission · attempt 1/5</button><button className="wf-link" onClick={onExit}>Back to games</button></section>}
    {screen==='attempt'&&<section className="wf-overlay"><p className="eyebrow">RUN {attempts.length} CONCLUDED</p><h2 className={last.success?'success':'failure'}>{last.success?'PORTALS SYNCHRONIZED':'MISSION INTERRUPTED'}</h2><p>{last.cause}</p><div className="wf-stats"><span>Gems <b>{last.gems}/10</b></span><span>Base <b>{last.base}</b></span><span>Time bonus <b>{last.timeBonus}</b></span><span>Total <b>{last.total}</b></span></div><button className="wf-primary" onClick={start}>Start attempt {attempts.length+1}/5</button><button className="wf-link" onClick={onExit}>Back to games</button></section>}
    {screen==='complete'&&<section className="wf-overlay"><p className="eyebrow">SESSION COMPLETE</p><h2>Dual-agent report</h2><div className="wf-stats"><span>Best run <b>{summary.bestScore}</b></span><span>Points awarded <b>{summary.points}</b></span></div><ol>{attempts.map((a,i)=><li key={i}><span>Run {i+1}</span><b>{a.score}</b><em>{a.success?'SUCCESS':'FAILED'}</em></li>)}</ol><button className="wf-primary" onClick={reset}>Replay session</button><button className="wf-link" onClick={onExit}>Back to games</button></section>}
    <nav className="wf-touch"><div><small>FIRE</small>{touch('fireLeft')}{touch('fireJump')}{touch('fireRight')}</div><div><small>WATER</small>{touch('waterLeft')}{touch('waterJump')}{touch('waterRight')}</div></nav>
  </div></main>
}
