'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowRight, Cloud, ShieldCheck } from 'lucide-react';
import { createClient, isSupabaseConfigured } from '@/lib/supabase';
export default function LoginPage(){
 const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [denied,setDenied]=useState(false);
 useEffect(()=>{const params=new URLSearchParams(location.search);setDenied(params.get('error')==='unauthorized_email');const message=params.get('message');if(message)setError(message)},[]);
 async function signIn(){if(!isSupabaseConfigured()){setError('Configuration required: add the Supabase URL and anonymous key to .env.local.');return}setLoading(true);setError('');const {error:e}=await createClient().auth.signInWithOAuth({provider:'google',options:{redirectTo:`${location.origin}/auth/callback`,queryParams:{access_type:'offline',prompt:'select_account'}}});if(e){setError(e.message);setLoading(false)}}
 return <main className="relative min-h-screen overflow-hidden"><div className="scanline" aria-hidden="true"/><header className="shell flex items-center justify-between py-6"><Link href="/" className="flex items-center gap-3 font-mono text-xs tracking-[.18em]"><span className="grid h-10 w-10 place-items-center bg-accent font-bold text-bg">AWS</span><span>STUDENT BUILDER GROUP<br/><span className="text-muted">VIT VELLORE</span></span></Link><span className="hidden font-mono text-[10px] tracking-[.18em] text-dim sm:block">SECURE_ACCESS / GOOGLE_OAUTH</span></header>
 <section className="shell grid min-h-[calc(100vh-88px)] items-center gap-12 py-14 lg:grid-cols-[1.2fr_.8fr]"><div><p className="eyebrow mb-6">AWS-SBG / RECRUITMENT_2026</p><h1 className="max-w-3xl text-5xl font-bold leading-[.94] tracking-[-.06em] sm:text-7xl lg:text-8xl">BUILD.<br/>PROVE.<br/><span className="text-accent">JOIN.</span></h1><p className="mt-8 max-w-md text-lg leading-8 text-muted">Your recruitment journey starts here. One identity, one focused path from assessment to interview.</p></div>
 <div className="technical-panel p-7 sm:p-9"><div className="mb-8 flex items-start justify-between border-b border-border pb-6"><div><p className="eyebrow">IDENTITY_GATEWAY</p><h2 className="mt-2 text-xl">Candidate access</h2></div><Cloud className="text-accent" aria-hidden="true"/></div>{denied&&<div role="alert" className="mb-6 border-l-2 border-error bg-error/10 p-4"><p className="font-mono text-xs text-error">ACCESS DENIED</p><p className="mt-2 text-sm leading-6 text-muted">This Google account is not eligible. Use your approved student account.</p></div>}{error&&<p role="alert" className="mb-5 border border-error/40 p-3 text-sm text-error">{error}</p>}<button onClick={signIn} disabled={loading} className="action w-full"><span className="grid h-6 w-6 place-items-center border border-bg/40 bg-white font-bold text-[#4285F4]">G</span>{loading?'Connecting…':'Continue with Google'}<ArrowRight size={16}/></button><div className="mt-6 flex gap-3 text-xs leading-5 text-dim"><ShieldCheck className="mt-0.5 shrink-0 text-blue" size={16}/><p>Authentication is handled by Supabase Auth. AWS-SBG never receives your Google password.</p></div></div></section></main>
}
