import React from'react';
import{useCallback,useEffect,useState}from'react';import{STORAGE_KEY,MORSE_MAP,buildCompletionPayload,closeChart,createState,openChart,questionRemainingAt,restoreState,serializeState,submitAnswer,syncState}from'./morseCore.js';import'./morse.css';
const load=()=>{try{return restoreState(localStorage.getItem(STORAGE_KEY),Date.now())}catch{return null}};
export function MorseGame({onComplete,onExit}){const[saved,setSaved]=useState(load);const[state,setState]=useState(null);const[screen,setScreen]=useState('landing');const[input,setInput]=useState('');const[msg,setMsg]=useState('');const[,tick]=useState(0);const persist=s=>{setState(s);if(s.official){localStorage.setItem(STORAGE_KEY,serializeState(s));setSaved(s)}};
 const notify=useCallback(s=>{if(!s.official||s.completionNotifiedAt)return;const p=buildCompletionPayload(s);window.dispatchEvent(new CustomEvent('aws-morse:complete',{detail:p}));try{window.AWSMorseOnComplete?.(p)}catch(e){console.error(e)}onComplete?.(p);persist({...s,completionNotifiedAt:Date.now()})},[onComplete]);
 const begin=official=>{const s=createState({official});persist(s);setScreen('game');setMsg('');setInput('')};
 useEffect(()=>{if(screen!=='game'||state?.status!=='active'||state.chartOpenedAt!==null)return;const id=setInterval(()=>{const n=syncState(state,Date.now());if(n!==state){persist(n);if(n.status==='complete'){notify(n);setScreen('result')}}tick(x=>x+1)},100);return()=>clearInterval(id)},[screen,state,notify]);
 const submit=e=>{e.preventDefault();const r=submitAnswer(state,input,Date.now());persist(r.state);setMsg(r.error||`Correct +${r.points}`);setInput('');if(r.state.status==='complete'){notify(r.state);setScreen('result')}};
 if(screen==='landing')return <div className="aws-morse"><div className="checks"/><main className="landing"><p className="eyebrow">AWS GAME SYSTEM // MORSE PROTOCOL</p><h1>READ THE<br/><span>SIGNAL.</span></h1><p>Five transmissions. Fifteen seconds each. Two reference opens per signal.</p><button onClick={()=>saved?(saved.status==='active'?(setState(saved),setScreen('game')):(setState(saved),setScreen('result'))):begin(true)}>{!saved?'START OFFICIAL ATTEMPT':saved.status==='active'?'RESUME ATTEMPT':'VIEW OFFICIAL RESULT'}</button></main></div>;
 if(screen==='result'){const s=state||saved;return <div className="aws-morse"><main className="result"><p className="eyebrow">{s.official?'OFFICIAL':'PRACTICE'} // COMPLETE</p><h2>TRANSMISSION COMPLETE</h2><div className="score">{s.score}<small>/50</small></div><p>{s.correctCount}/5 signals decoded.</p><div className="actions"><button onClick={()=>begin(false)}>PRACTICE RETRY</button><button className="ghost" onClick={()=>onExit?onExit():setScreen('landing')}>BACK TO LANDING PAGE</button></div></main></div>}
 const q=state.questions[state.questionIndex],remaining=Math.ceil(questionRemainingAt(state)/1000),chart=state.chartOpenedAt!==null;return <div className="aws-morse"><header><b>AWS MORSE DECODER</b><span>{state.official?'OFFICIAL':'PRACTICE'} · {state.questionIndex+1}/5 · {remaining}s · {state.score} pts</span></header><main className="game"><p className="eyebrow">SIGNAL {state.questionIndex+1}</p><div className="signal">{q.signal}</div><form onSubmit={submit}><input autoFocus value={input} onChange={e=>setInput(e.target.value.toUpperCase())} placeholder="TYPE DECODE"/><button>SUBMIT</button></form>{msg&&<p className="message">{msg}</p>}<button className="reference" disabled={!state.referenceOpensRemaining} onClick={()=>persist(openChart(state))}>REFERENCE ({state.referenceOpensRemaining})</button></main>{chart&&<div className="modal"><div><h2>INTERNATIONAL MORSE</h2><section>{Object.entries(MORSE_MAP).map(([l,s])=><span key={l}><b>{l}</b>{s}</span>)}</section><button onClick={()=>persist(closeChart(state))}>CLOSE REFERENCE</button></div></div>}</div>}
export default MorseGame;
