export const STORAGE_KEY='aws-builder-wordle:v1';
export const MAX_GUESSES=6;
export function scoreForAttempt(n,solved){return solved?Math.max(50,110-n*10):0}
export function evaluateGuess(rawGuess,rawAnswer){const guess=rawGuess.toUpperCase(),answer=rawAnswer.toUpperCase(),states=Array(5).fill('absent'),left={};for(let i=0;i<5;i++){if(guess[i]===answer[i])states[i]='correct';else left[answer[i]]=(left[answer[i]]||0)+1}for(let i=0;i<5;i++){if(states[i]==='correct')continue;const l=guess[i];if(left[l]>0){states[i]='present';left[l]--}}return states}
export function submitGuess(state,raw,valid){if(state.status!=='active')return{state,error:'Attempt already completed',completed:false};const guess=raw.trim().toUpperCase();if(guess.length!==5)return{state,error:'Not enough letters',completed:false};if(!valid.has(guess))return{state,error:'Not in word list',completed:false};const guesses=[...state.guesses,guess],solved=guess===state.answer,exhausted=guesses.length>=MAX_GUESSES,completed=solved||exhausted;return{state:{...state,guesses,status:solved?'won':exhausted?'lost':'active',score:completed?scoreForAttempt(guesses.length,solved):null},error:null,completed}}
export function createAttempt(solutions,random=Math.random,now=()=>new Date().toISOString(),attemptId=globalThis.crypto?.randomUUID?.()||`attempt-${Date.now()}`){return{version:1,attemptId,answer:solutions[Math.floor(random()*solutions.length)].toUpperCase(),guesses:[],status:'active',score:null,startedAt:now(),completedAt:null,completionNotified:false}}
export function normalizeWordData(data){if(!Array.isArray(data?.solutions)||!Array.isArray(data?.guesses))throw new Error('Word data is invalid');return{solutions:data.solutions,validWords:new Set([...data.solutions,...data.guesses])}}
export function finalizeCompletedState(state,now=()=>new Date().toISOString()){return{...state,completedAt:state.completedAt||now(),completionNotified:false}}
export function formatResultMessage(s){return s.status==='won'?`Solved in ${s.guesses.length} transmission${s.guesses.length===1?'':'s'}. Correct answer: ${s.answer}. Your attempt is now locked.`:`Signal lost. Correct answer: ${s.answer}. Your attempt is now locked.`}
export function buildPayload(s){return{attemptId:s.attemptId,guesses:[...s.guesses],solved:s.status==='won',attemptsUsed:s.guesses.length,score:s.score,startedAt:s.startedAt,completedAt:s.completedAt}}
