export const VERSION=1,STORAGE_KEY='aws-morse:v1',QUESTION_MS=15000,REFERENCE_OPENS_PER_QUESTION=2;
export const MORSE_MAP=Object.freeze({A:'.-',B:'-...',C:'-.-.',D:'-..',E:'.',F:'..-.',G:'--.',H:'....',I:'..',J:'.---',K:'-.-',L:'.-..',M:'--',N:'-.',O:'---',P:'.--.',Q:'--.-',R:'.-.',S:'...',T:'-',U:'..-',V:'...-',W:'.--',X:'-..-',Y:'-.--',Z:'--..',0:'-----',1:'.----',2:'..---',3:'...--',4:'....-',5:'.....',6:'-....',7:'--...',8:'---..',9:'----.'});
const pools={a:['E','T'],b:['A','N','I','M'],easy:['API','WEB','LOG','RUN','CAT'],hard:['CODE','CLOUD','BUILD','SERVER','LAMBDA']};
export function encodeMorse(v){return String(v).trim().toUpperCase().split(' ').map(w=>[...w].map(c=>MORSE_MAP[c]||'').filter(Boolean).join(' ')).join(' / ')}
const pick=(p,r)=>p[Math.floor(Math.min(Math.max(Number(r())||0,0),.999999)*p.length)];
export function buildQuestionSet(r=Math.random){return[pick(pools.a,r),pick(pools.b,r),'AWS',pick(pools.easy,r),pick(pools.hard,r)].map((answer,i)=>({answer,level:i+1,signal:encodeMorse(answer)}))}
export function pointsForRemaining(ms){return ms<=0?0:ms>=11250?10:ms>=7500?9:ms>=3750?8:7}
export function createState({official=true,now=Date.now(),attemptId=globalThis.crypto?.randomUUID?.()||`morse-${now}`,random=Math.random}={}){return{version:1,attemptId,official,status:'active',questionIndex:0,score:0,correctCount:0,questions:buildQuestionSet(random),results:[],wrongAttempts:0,startedAt:now,completedAt:null,questionStartedAt:now,questionDeadlineAt:now+QUESTION_MS,referenceOpensRemaining:2,chartOpensUsed:0,chartOpenedAt:null,pausedQuestionRemainingMs:null,completionNotifiedAt:null}}
function advance(s,result,now){const results=[...s.results,result],score=s.score+result.points,correctCount=s.correctCount+(result.outcome==='correct'?1:0),done=results.length===5;return{...s,status:done?'complete':'active',questionIndex:done?s.questionIndex:s.questionIndex+1,score,correctCount,results,wrongAttempts:0,completedAt:done?now:null,questionStartedAt:done?null:now,questionDeadlineAt:done?null:now+QUESTION_MS,referenceOpensRemaining:2}}
function timeout(s,now){const q=s.questions[s.questionIndex];return advance(s,{questionIndex:s.questionIndex,answer:q.answer,signal:q.signal,outcome:'timeout',points:0,answeredAt:now,elapsedMs:QUESTION_MS,wrongAttempts:s.wrongAttempts,referenceOpensUsed:2-s.referenceOpensRemaining},now)}
export function submitAnswer(s,raw,now=Date.now()){if(s.status!=='active')return{state:s,error:'This attempt is already complete.',correct:false};if(s.chartOpenedAt!==null)return{state:s,error:'Close the reference chart before answering.',correct:false};if(now>=s.questionDeadlineAt)return{state:timeout(s,now),error:'Signal expired.',correct:false,timedOut:true,points:0};const a=String(raw??'').trim().toUpperCase();if(!a)return{state:s,error:'Enter an answer first.',correct:false};if(!/^[A-Z0-9]+$/.test(a))return{state:s,error:'Use letters and numbers only.',correct:false};const q=s.questions[s.questionIndex];if(a!==q.answer)return{state:{...s,wrongAttempts:s.wrongAttempts+1},error:'Signal mismatch. Try again.',correct:false};const rem=Math.max(0,s.questionDeadlineAt-now),points=pointsForRemaining(rem);return{state:advance(s,{questionIndex:s.questionIndex,answer:q.answer,signal:q.signal,outcome:'correct',points,answeredAt:now,elapsedMs:QUESTION_MS-rem,wrongAttempts:s.wrongAttempts,referenceOpensUsed:2-s.referenceOpensRemaining},now),error:null,correct:true,points}}
export function openChart(s,now=Date.now()){if(s.status!=='active'||s.chartOpenedAt!==null||s.referenceOpensRemaining<=0)return s;if(now>=s.questionDeadlineAt)return timeout(s,now);return{...s,referenceOpensRemaining:s.referenceOpensRemaining-1,chartOpensUsed:s.chartOpensUsed+1,chartOpenedAt:now,pausedQuestionRemainingMs:Math.max(0,s.questionDeadlineAt-now),questionDeadlineAt:null}}
export function closeChart(s,now=Date.now()){return s.chartOpenedAt===null?s:{...s,chartOpenedAt:null,questionDeadlineAt:now+s.pausedQuestionRemainingMs,pausedQuestionRemainingMs:null}}
export const questionRemainingAt=(s,now=Date.now())=>s.status!=='active'?0:s.chartOpenedAt!==null?s.pausedQuestionRemainingMs:Math.max(0,s.questionDeadlineAt-now);
export const syncState=(s,now=Date.now())=>!s||s.status!=='active'||s.chartOpenedAt!==null?s:now>=s.questionDeadlineAt?timeout(s,now):s;
export const serializeState=s=>JSON.stringify(s);
export function restoreState(raw,now=Date.now()){try{const s=JSON.parse(raw);if(s?.version!==1||s.official!==true||!['active','complete'].includes(s.status)||!Array.isArray(s.questions)||s.questions.length!==5)return null;return syncState(s,now)}catch{return null}}
export const buildCompletionPayload=s=>({game:'aws-morse-decoder',version:1,attemptId:s.attemptId,official:s.official,score:s.score,correctCount:s.correctCount,totalQuestions:5,results:s.results,startedAt:s.startedAt,completedAt:s.completedAt,chartOpensUsed:s.chartOpensUsed});
